dasum:
	nvcc dasum.c -o dasum --cudart=shared
daxpy:
	nvcc daxpy.c -o daxpy --cudart=shared
ddot:
	nvcc ddot.c -o ddot --cudart=shared
dscal:
	nvcc dscal.c -o dscal --cudart=shared
sasum:
	nvcc sasum.c -o sasum --cudart=shared
saxpy:
	nvcc saxpy.c -o saxpy --cudart=shared
scopy:
	nvcc scopy.c -o scopy --cudart=shared
sdot:
	nvcc sdot.c -o sdot --cudart=shared
sgemm:
	nvcc sgemm.c -o sgemm --cudart=shared
sgemv:
	nvcc sgemv.c -o sgemv --cudart=shared
sscal:
	nvcc sscal.c -o sscal --cudart=shared


clean:
	rm dasum daxpy ddot dscal sasum saxpy scopy sdot sgemm sgemv sscal